name: Run Update

on:
  repository_dispatch:
    types: [my-event]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requests module
        run: pip install requests
      - name: Install yaml module
        run: pip install pyyaml
      - name: setup Github environment
        run: |
          #setup username and email to use Github Actions Bot with no default email
          git config user.name "Github Actions Bot"
          git config user.email "<>"
      - name: Checkout remote main branch
        uses: actions/checkout@v2
        with:
          repository: leethomasrh/cop
          ref: main
          token: ${{ secrets.PAT }}
          path: ./cop
      - name: Run COP update
        shell: bash
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          echo "checkout main branch" &&
          git remote add main "https://${{ secrets.PAT }}@github.com/leethomasrh/cop.git" &&
          git fetch main &&
          python cop_bazaar.py &&
          mv ./cop/output ./cop/output2
          echo "checkout output branch" &&
          git remote add output "https://${{ secrets.PAT }}@github.com/leethomasrh/cop.git" &&
          git fetch output &&
          mv ./cop/output2 ./cop/output &&
          git add ./cop/output &&
          git commit -m "Updating output via gitaction" &&
          git push
