name: Run Update

on:
  repository_dispatch:
    types: [my-event]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requests module
        run: pip install requests
      - name: Install yaml module
        run: pip install pyyaml
      - name: setup Github environment
        run: |
          #setup username and email to use Github Actions Bot with no default email
          git config user.name "Github Actions Bot"
          git config user.email "<>"
      - name: Checkout remote action
        uses: actions/checkout@v2
        with:
          repository: leethomasrh/cop
          token: ${{ secrets.PAT }}
          path: cop
      - name: Update COP List
        shell: bash
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          python cop_bazaar.py &&
          mv output output2 &&
          echo "checkout output branch" &&
          git remote update &&
          git fetch &&
          git branch &&
          git checkout leethomasrh/cop/output &&
          echo "rm output folder and move updated output folder" &&
          rm -rf output &&
          mv output2 output &&
          echo "add, commit and push output update" &&
          git add output &&
          git commit -m "Updating output via gitaction" &&
          git push