name: Run Update

on:
  repository_dispatch:
    types: [my-event]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requests module
        run: pip install requests
      - name: Install yaml module
        run: pip install pyyaml
      - name: setup Github environment
        run: |
          #setup username and email to use Github Actions Bot with no default email
          git config user.name "Github Actions Bot"
          git config user.email "<>"
      - name: Checkout remote main branch
        uses: actions/checkout@v2
        with:
          repository: leethomasrh/cop@
          ref: main
          token: ${{ secrets.PAT }}
          path: ./cop
      - name: Run COP update
        shell: bash
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          python cop_bazaar.py
      - name: Checkout remote output branch
        uses: actions/checkout@v2
        with:
          repository: leethomasrh/cop
          ref: output
          token: ${{ secrets.PAT }}
          path: ./cop-output
      - name: Update COP List
        shell: bash
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          echo "rm output folder and move updated output folder" &&
          rm -rf ./cop-output/output &&
          cp ./cop/output ./cop-output/output &&
          echo "add, commit and push output update" &&
          git add ./cop-output/output &&
          git commit -m "Updating output via gitaction" &&
          git push
#          echo "checkout output branch" &&
#          git remote update &&
#          git fetch &&
#          git branch &&
#          git branch -v -a &&
#          git checkout output &&