name: Run Update

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl --url https://raw.githubusercontent.com/leethomasrh/cop-bazaar/master/cop_bazaar.py --header 'authorization: Bearer ${{ secrets.TOKEN }}' > /tmp/cop_bazaar.tmp.py && cat /tmp/cop_bazaar.tmp.py
      - name: Display python version
        run: python -V
      - name: Display installed pips
        run: pip list    
      - name: Install requests module
        run: pip install requests
      - name: Install yaml module
        run: pip install pyyaml
      - name: Display installed pips
        run: pip list 
      - name: Update COP List
        run: |
          python cop_bazaar.py

